### ISSUE TITLE
Is there a way to use the controls programmatically?

### ISSUE THREAD

**Issue by vahost** [dongido001/vue-viaudio#5]
I like your plugin!

Is there is a way to play or pause the player using a watcher, computed property, or method?

**Comment by dongido001** [comment]
Sure you can @vahost

sorry, didn't get a notification for this issue :( 

I think this is an example of [what you are asking about](https://github.com/dongido001/vue-viaudio#a-bit-advanced-usage---with-events)

**Comment by dongido001** [comment]
closing, feel free to comment or open if you still have questions
